TRAIN: 
  AE:
    BATCH_SIZE: 2
    EPOCH: 300
  TREATMENT_CLASS:
    BATCH_SIZE: 2
    EPOCH: 30

TEST:
  BATCH_SIZE: 6

OPTIMIZER:
  lr: 0.0005

MODEL:
  AE:
    N_LATENT: 150
    MODEL_PATH: '/media/jerrynas/Research/LeafSpec/Models/HSI Deep Learning Model/Jan2020'
    OUTPUT_SIZE: [150, 124, 109]
    LAYER_CHANNEL: [360,350,340,330,320,310,300,290,280,270,260,250,240,230,220,210,200,190,180,170,160,150,140,130,120,110,100,90,80,70,60,50,40,30,20,10,1]
    MAXPOOL_AFTER: 3
    STRIDE_BEFORE: 1
  TREATMENT_CLASS:
    N_CLASSES: 1
    N_STAGES: 3

DATASET:
  N_WAVELENGTH: 360
  DATA_DIR: '/media/jerrynas/Research/LeafSpec/SoyBean Device Data/Sumitomo 2020/Raw Data'
  MAX_LENGTH: 201
  MAX_WIDTH: 241
  ROTATE_IMAGE: True
  FLIP_HORIZONTAL: True
  FLIP_VERTICAL: True
  CLASSES: {
    '6825': 1.0,
    '6826': 0.0,
    '6827': 0.0,
    '6828': 1.0,
    '6829': 1.0,
    '6830': 0.0
  }

HSI:
  NDVI_THRESH: 0.45
  PST2WV: [1.3178, 442.2233]
  WV2PST: [0.7588, -335.5678]