TRAIN: 
  AE:
    BATCH_SIZE: 4
    EPOCH: 5000
  TREATMENT_CLASS:
    BATCH_SIZE: 4
    EPOCH: 100

TEST:
  BATCH_SIZE: 6

OPTIMIZER:
  lr: 0.0001

MODEL:
  AE:
    N_LATENT: 150
    MODEL_PATH: '/media/jerrynas/Research/LeafSpec/HSI Deep Learning Model'
    OUTPUT_SIZE: [150, 124, 109]
  TREATMENT_CLASS:
    N_CLASSES: 1
    N_STAGES: 3

DATASET:
  N_WAVELENGTH: 360
  DATA_DIR: '/media/jerrynas/Research/LeafSpec/SoyBean Device Data/Sumitomo 2020/Raw Data'
  MAX_LENGTH: 211
  MAX_WIDTH: 241
  ROTATE_IMAGE: True
  FLIP_HORIZONTAL: True
  FLIP_VERTICAL: True
  CLASSES: {
    '6025': 1,
    '6026': 0,
    '6027': 0,
    '6028': 1,
    '6029': 1,
    '6030': 0
  }

HSI:
  NDVI_THRESH: 0.45
  PST2WV: [1.3178, 442.2233]
  WV2PST: [0.7588, -335.5678]